### ISSUE TITLE
Task nmap-tcp returned non-zero exit code: 255

### ISSUE THREAD

**Issue by lianfeng30** [RoliSoft/ReconScan#3]
python3.6 recon.py -v 119.0.1.1-254
[*] Scanning host 119.0.1.1-254...
[*] Running task nmap-tcp with nmap -vv --reason -sV -sC -Pn --min-rate=400 -T4 --script-timeout 10m -p- -oN "results/119.0.1.1-254/0_tcp_nmap.txt" -oX "results/119.0.1.1-254/0_tcp_nmap.xml" 119.0.1.1-254
[!] Task nmap-tcp returned non-zero exit code: 255
[*] Running task nmap-udp with nmap -vv --reason -sV --version-intensity 0 -sC -sU -Pn --min-rate=400 -T4 --script-timeout 10m -oN "results/119.0.1.1-254/0_udp_nmap.txt" -oX "results/119.0.1.1-254/0_udp_nmap.xml" 119.0.1.1-254
[!] Task nmap-udp returned non-zero exit code: 255

virtualenv --python=/usr/bin/python3.6 venv
Running virtualenv with interpreter /usr/bin/python3.6
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 8, in <module>
    import base64
  File "/usr/python3/lib/python3.6/base64.py", line 9, in <module>
    import re
  File "/usr/python3/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

**Comment by thistehneisen** [comment]
Having the same issue.

**Comment by hxer** [comment]
exit code:255, actually, this indicates that nmap returns -1. Maybe nmap's args is error. 
More can see [http://www.beesfun.com/2017/11/30/%E3%80%90develop%E3%80%91nmap-exit-code-255/](http://www.beesfun.com/2017/11/30/%E3%80%90develop%E3%80%91nmap-exit-code-255/)
